package Pojo;




/**
 * Student generated by java
 */
public class Student  implements java.io.Serializable {


     private String id;
     private String name;
     private int batch;
     private String department;
     private byte[] avatar;

    public Student() {
    }

    public Student(String id, String name, int batch, String department, byte[] avatar) {
       this.id = id;
       this.name = name;
       this.batch = batch;
       this.department = department;
       this.avatar = avatar;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getBatch() {
        return this.batch;
    }
    
    public void setBatch(int batch) {
        this.batch = batch;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public byte[] getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(byte[] avatar) {
        this.avatar = avatar;
    }




}


