package Pojo;



/**
 * User generated by java
 */
public class User  implements java.io.Serializable {


     private String userId;
     private String password;

    public User() {
    }

    public User(String userId, String password) {
       this.userId = userId;
       this.password = password;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


